name: setup_app
description: "Unotusk Server Setup Desktop Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0-282.1.beta

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.2.0

  # Networking
  dio: ^5.5.0+1

  # Process Execution for Deployment & System Validation
  process_run: ^1.1.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
