#!/usr/bin/env bash
# ==============================================================================
# UNOTUSK Bootstrap Script
# Health-aware service startup with dependency ordering:
#   postgres → us → ups → ai-pie
# ==============================================================================
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/unotusk}"
WIZARD_CONF="$INSTALL_DIR/.env.wizard"
SECRETS_FILE="$INSTALL_DIR/.secrets"
LOG_DIR="$INSTALL_DIR/logs"
BOOTSTRAP_LOG="$LOG_DIR/bootstrap.log"

cd "$INSTALL_DIR"
mkdir -p "$LOG_DIR"

# ── Colour helpers ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "  ${CYAN}→${RESET} $*" | tee -a "$BOOTSTRAP_LOG"; }
success() { echo -e "  ${GREEN}✔${RESET} $*" | tee -a "$BOOTSTRAP_LOG"; }
warn()    { echo -e "  ${YELLOW}⚠${RESET} $*" | tee -a "$BOOTSTRAP_LOG"; }
fail()    { echo -e "  ${RED}✘${RESET} $*" | tee -a "$BOOTSTRAP_LOG"; exit 1; }
step()    { echo -e "\n${BOLD}$*${RESET}" | tee -a "$BOOTSTRAP_LOG"; }

echo "" | tee -a "$BOOTSTRAP_LOG"
echo -e "${BOLD}╔══════════════════════════════════════════╗${RESET}" | tee -a "$BOOTSTRAP_LOG"
echo -e "${BOLD}║         UNOTUSK Bootstrap                ║${RESET}" | tee -a "$BOOTSTRAP_LOG"
echo -e "${BOLD}╚══════════════════════════════════════════╝${RESET}" | tee -a "$BOOTSTRAP_LOG"
echo "" | tee -a "$BOOTSTRAP_LOG"

# ── Load wizard configuration ──────────────────────────────────────────────────
if [ -f "$WIZARD_CONF" ]; then
  # shellcheck source=/dev/null
  source "$WIZARD_CONF"
fi
if [ -f "$SECRETS_FILE" ]; then
  # shellcheck source=/dev/null
  source "$SECRETS_FILE"
fi

# Fallbacks for unattended mode
ORG_NAME="${ORG_NAME:-UnotuskCustomer}"
LICENSE_KEY="${LICENSE_KEY:-DEMO-LICENSE-KEY}"
PLATFORM_URL="${PLATFORM_URL:-https://platform.unotusk.com:50051}"
OAUTH_PROVIDER="${OAUTH_PROVIDER:-}"
OAUTH_CLIENT_ID="${OAUTH_CLIENT_ID:-}"
OAUTH_CLIENT_SECRET="${OAUTH_CLIENT_SECRET:-}"
OAUTH_REDIRECT_URI="${OAUTH_REDIRECT_URI:-}"

# ── Helpers ────────────────────────────────────────────────────────────────────
generate_password() {
  head -c 48 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32
}

generate_uuid() {
  if command -v uuidgen &>/dev/null; then
    uuidgen | tr '[:upper:]' '[:lower:]'
  else
    cat /proc/sys/kernel/random/uuid
  fi
}

# ── Health-aware service wait ──────────────────────────────────────────────────
# wait_healthy <service_name> <timeout_seconds>
wait_healthy() {
  local service="$1"
  local timeout="${2:-120}"
  local elapsed=0
  local interval=5
  local container_id

  container_id=$(docker compose ps -q "$service" 2>/dev/null || true)
  if [ -z "$container_id" ]; then
    fail "Service '$service' has no running container after 'up -d'."
  fi

  info "Waiting for '$service' to become healthy (timeout ${timeout}s)..."

  while [ "$elapsed" -lt "$timeout" ]; do
    local status
    status=$(docker inspect --format='{{if .State.Health}}{{.State.Health.Status}}{{else}}running{{end}}' "$container_id" 2>/dev/null || echo "unknown")

    case "$status" in
      healthy|running)
        # "running" means no healthcheck defined — treat as pass
        success "  $service is healthy."
        return 0
        ;;
      unhealthy)
        fail "Service '$service' entered unhealthy state. Check logs: docker compose logs $service"
        ;;
      starting)
        printf "  . " ; sleep "$interval" ; elapsed=$((elapsed + interval))
        ;;
      *)
        sleep "$interval" ; elapsed=$((elapsed + interval))
        ;;
    esac
  done

  fail "Service '$service' did not become healthy within ${timeout}s. Check: docker compose logs $service"
}

# ── Step 1: Generate secrets ───────────────────────────────────────────────────
step "[1/5] Generating secrets and configuration..."

# Do not regenerate if already present (idempotency: resume after partial failure)
ENV_FILE="$INSTALL_DIR/.env"
if [ -f "$ENV_FILE" ] && grep -q "^POSTGRES_PASSWORD=" "$ENV_FILE"; then
  info "Root .env already exists — loading existing secrets."
  # shellcheck source=/dev/null
  source "$ENV_FILE"
else
  POSTGRES_PASSWORD=$(generate_password)
  QDRANT_API_KEY=$(generate_password)
  JWKS_PUSH_SECRET=$(generate_password)
  ORG_ID=$(generate_uuid)

  cat > "$ENV_FILE" <<EOF
# UNOTUSK stack — generated by bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do not edit this file manually. Use 'unotusk reconfigure' to change settings.

POSTGRES_USER=unotusk
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=unotusk

QDRANT_API_KEY=${QDRANT_API_KEY}

PLATFORM_URL=${PLATFORM_URL}
PLATFORM_LICENSE_KEY=${LICENSE_KEY}

ORG_ID=${ORG_ID}
JWKS_PUSH_SECRET=${JWKS_PUSH_SECRET}

PLATFORM_TOKEN_AUDIENCE=platform.unotusk.com
PLATFORM_JWKS_PUSH_URL=https://platform.unotusk.com/internal/orgs/${ORG_ID}/jwks
EOF
  chmod 600 "$ENV_FILE"
fi

# Source generated env for rest of script
# shellcheck source=/dev/null
source "$ENV_FILE"

# Service dirs
mkdir -p US UPS AI-PIE

# US/.env — only write if not present (idempotent)
if [ ! -f "US/.env" ]; then
  cat > US/.env <<EOF
LOG_LEVEL=info
PLATFORM_TOKEN_AUDIENCE=${PLATFORM_TOKEN_AUDIENCE:-platform.unotusk.com}
EOF
fi

# UPS/.env
if [ ! -f "UPS/.env" ]; then
  cat > UPS/.env <<EOF
LOG_LEVEL=info
LICENSE_HEARTBEAT_INTERVAL=60
LICENSE_GRACE_PERIOD=18000
PLATFORM_JWKS_PUSH_URL=${PLATFORM_JWKS_PUSH_URL}
EOF
fi

# AI-PIE/.env — store OAuth secrets here if provider configured
if [ ! -f "AI-PIE/.env" ]; then
  cat > AI-PIE/.env <<EOF
LOG_LEVEL=info
EOF
fi

# Write OAuth secrets into service env if configured
if [ -n "$OAUTH_PROVIDER" ]; then
  {
    echo "OAUTH_PROVIDER=${OAUTH_PROVIDER}"
    echo "OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}"
    echo "OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}"
  } >> US/.env
  # Secret goes in a separate file, not in the primary .env
  OAUTH_SECRET_FILE="$INSTALL_DIR/.oauth.secret"
  echo "OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}" > "$OAUTH_SECRET_FILE"
  chmod 600 "$OAUTH_SECRET_FILE"
fi

chmod 600 US/.env UPS/.env AI-PIE/.env 2>/dev/null || true
success "Configuration files written."

# ── Step 2: TLS certificates ───────────────────────────────────────────────────
step "[2/5] Setting up TLS certificates..."

mkdir -p US/certs UPS/certs/platform AI-PIE/certs/dev

CERT_MARKER="$INSTALL_DIR/.certs-generated"
if [ ! -f "$CERT_MARKER" ]; then
  info "Generating local CA and service certificates..."

  # Root CA
  openssl req -x509 -newkey rsa:4096 -days 3650 -nodes \
    -keyout US/certs/ca.key -out US/certs/ca.crt \
    -subj "/C=IN/O=Unotusk/CN=UnotuskLocalCA" \
    2>>"$BOOTSTRAP_LOG"

  # US server cert
  openssl req -newkey rsa:2048 -nodes \
    -keyout US/certs/server.key -out US/certs/server.csr \
    -subj "/C=IN/O=Unotusk/CN=auth-server" 2>>"$BOOTSTRAP_LOG"
  openssl x509 -req -in US/certs/server.csr -CA US/certs/ca.crt -CAkey US/certs/ca.key \
    -CAcreateserial -out US/certs/server.crt -days 365 2>>"$BOOTSTRAP_LOG"

  # Copy CA to other services
  cp US/certs/ca.crt UPS/certs/ca.crt
  cp US/certs/ca.crt AI-PIE/certs/ca.crt

  # UPS client cert (for mTLS to US)
  openssl req -newkey rsa:2048 -nodes \
    -keyout UPS/certs/client.key -out UPS/certs/client.csr \
    -subj "/C=IN/O=Unotusk/CN=company-server" 2>>"$BOOTSTRAP_LOG"
  openssl x509 -req -in UPS/certs/client.csr -CA US/certs/ca.crt -CAkey US/certs/ca.key \
    -CAcreateserial -out UPS/certs/client.crt -days 365 2>>"$BOOTSTRAP_LOG"

  # Platform dummy certs for UPS (used until real Platform certs are provisioned)
  openssl req -x509 -newkey rsa:2048 -days 365 -nodes \
    -keyout UPS/certs/platform/client.key -out UPS/certs/platform/client.crt \
    -subj "/C=IN/O=Unotusk/CN=platform-client" 2>>"$BOOTSTRAP_LOG"
  cp UPS/certs/platform/client.crt UPS/certs/platform/ca.crt

  # AI-PIE dev cert (for its mTLS healthcheck)
  openssl req -newkey rsa:2048 -nodes \
    -keyout AI-PIE/certs/dev/client.key -out AI-PIE/certs/dev/client.csr \
    -subj "/C=IN/O=Unotusk/CN=ai-pie" 2>>"$BOOTSTRAP_LOG"
  openssl x509 -req -in AI-PIE/certs/dev/client.csr \
    -CA US/certs/ca.crt -CAkey US/certs/ca.key -CAcreateserial \
    -out AI-PIE/certs/dev/client.pem -days 365 2>>"$BOOTSTRAP_LOG"

  # Relax key permissions so bind-mounted containers can read them
  find US/certs UPS/certs AI-PIE/certs -name "*.key" -exec chmod 644 {} +

  touch "$CERT_MARKER"
  success "Certificates generated."
else
  success "Certificates already present — skipping generation."
fi

# ── Step 3: Docker volumes and networks ───────────────────────────────────────
step "[3/5] Preparing Docker volumes and networks..."
# docker compose creates these automatically on first 'up'; verify compose file is valid
if ! docker compose config --quiet 2>>"$BOOTSTRAP_LOG"; then
  fail "docker-compose.yml has configuration errors. Check the log: $BOOTSTRAP_LOG"
fi
success "Docker Compose configuration is valid."

# ── Step 4: Health-aware service startup ──────────────────────────────────────
step "[4/5] Starting services in dependency order..."

# Start infrastructure tier first
info "Starting postgres..."
docker compose up -d postgres
wait_healthy postgres 90

info "Starting qdrant and phoenix in parallel..."
docker compose up -d qdrant phoenix
wait_healthy qdrant 90
wait_healthy phoenix 90

# Auth service depends on postgres
info "Starting US (auth service)..."
docker compose up -d us
wait_healthy us 120

# Company server depends on postgres + us
info "Starting UPS (company server)..."
docker compose up -d ups
wait_healthy ups 120

# AI PIE depends on qdrant + phoenix + ups
info "Starting AI-PIE (intelligence engine)..."
docker compose up -d ai-pie
wait_healthy ai-pie 180

success "All services are healthy."

# ── Step 5: Record installation metadata ──────────────────────────────────────
step "[5/5] Finalising installation..."

VERSION_FILE="$INSTALL_DIR/.unotusk-version"
if [ ! -f "$VERSION_FILE" ]; then
  cat > "$VERSION_FILE" <<EOF
INSTALL_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
INSTALL_VERSION=0.2.0-rc1
ORG_ID=${ORG_ID}
ORG_NAME=${ORG_NAME}
EOF
fi
success "Installation metadata written to $VERSION_FILE"

echo "" | tee -a "$BOOTSTRAP_LOG"
echo -e "${BOLD}╔══════════════════════════════════════════╗${RESET}" | tee -a "$BOOTSTRAP_LOG"
echo -e "${BOLD}║       Bootstrap Complete  🎉             ║${RESET}" | tee -a "$BOOTSTRAP_LOG"
echo -e "${BOLD}╚══════════════════════════════════════════╝${RESET}" | tee -a "$BOOTSTRAP_LOG"
echo "" | tee -a "$BOOTSTRAP_LOG"
echo "  Run 'unotusk status'  to see container health." | tee -a "$BOOTSTRAP_LOG"
echo "  Run 'unotusk doctor'  to run full diagnostics." | tee -a "$BOOTSTRAP_LOG"
echo "" | tee -a "$BOOTSTRAP_LOG"
